[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
nalgebra-glm = "0.19.0"

[dev-dependencies]
image = "0.25.5"
nalgebra = "0.33.2"
sdl2 = "0.37.0"
tobj = "4.0.3"
